### ISSUE TITLE
26.06.2020 Peer to peer code review

### ISSUE THREAD

**Issue by shubham14p3** [sebGilR/endless_runner_game#3]
It was great seeing you complete the Capstone project of Javascript, and congrats on getting Mastery in all the field.
There was no feedback from our end so far, but we found a small bug, that we would like you to know 
"The score is not being reset when we retry to play the game after we lose", 
Kindly check on this and it will make your project more ondeful.
Key Points :
1. Great Game UI
2. Crisp and clean code

**Comment by sebGilR** [comment]
Thank you for the feedback, the issue with the score has been addressed.
